- name: install apache and php (Ubuntu)
  tags: apache,apache2,ubuntu
  apt:
    name:
      - apache2
      - libapache2-mod-php
    state: latest
  when: ansible_facts['distribution'] == "Ubuntu"

- name: install apache and php (CentOS)
  tags: apache,httpd,centos
  dnf:
    name:
      - httpd
      - php
    state: latest
  when: ansible_facts['distribution'] == "CentOS"

- name: start httpd (CentOS)
  tags: apache,centos,httpd
  service:
    name: httpd
    state: started
    enabled: yes
  when: ansible_facts['distribution'] == "CentOS"

- name: change e-mail address for admin (CentOS)
  tags: apache,centos,httpd
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: "^ServerAdmin"
    line: ServerAdmin somebody@somewhere.net
  when: ansible_facts['distribution'] == "CentOS"

- name: change server name (CentOS)
  tags: apache,centos,httpd
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: "^#ServerName"
    line: ServerName {{ inventory_hostname }}
  when: ansible_facts['distribution'] == "CentOS"
  register: httpd

- name: restart httpd (CentOS)
  tags: apache,centos,httpd
  service:
    name: httpd
    state: restarted
  when: httpd.changed

- name: copy default html file for site
  tags: apache,apache2,httpd
  copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644
